name: robodiff
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.0
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - numba=0.59.1
  - scipy=1.13.0
  - py-opencv=4.9.0
  - cffi=1.16.0
  - ipykernel=6.29.4
  - matplotlib=3.8.4
  - zarr=2.18.3
  - numcodecs=0.12.1
  - h5py=3.11.0
  - hydra-core=1.3.2
  - einops=0.8.0
  - tqdm=4.66.4
  - dill=0.3.8
  - scikit-video=1.1.11
  - scikit-image=0.23.2
  - pymunk=6.6.0
  - wandb=0.16.6
  - threadpoolctl=3.5.0
  - shapely=2.0.4
  - cython=3.0.11
  - imageio=2.34.1
  - imageio-ffmpeg=0.5.1
  - termcolor=2.4.0
  - tensorboard=2.16.2
  - tensorboardx=2.6.2
  - psutil=5.9.8
  - click=8.1.7
  - boto3=1.34.118
  - accelerate=0.30.1
  - datasets=2.20.0
  - diffusers=0.35.2
  - av=11.0.0
  - cmake=3.29.3
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625    
  - llvm-openmp=14
  - pip:
    - ray[default,tune]==2.9.3
    - gym==0.26.2
    # requires mujoco py dependencies libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
    - free-mujoco-py==2.1.6
    - pygame==2.5.2
    - pybullet==3.2.6
    - robosuite==1.5.1
    - robomimic==0.2.0
    - pytorchvideo==0.1.5
    # pip package required for jpeg-xl
    - imagecodecs==2024.12.30
    - pytorch3d @ https://github.com/facebookresearch/pytorch3d/archive/50f8efa1cbfbde1a8e70efda53756f7b9cea67a7.tar.gz
    - r3m @ https://github.com/facebookresearch/r3m/archive/b2334e726887fa0206962d7984c69c5fb09cceab.tar.gz    
    - dm-control==1.0.17