_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_workspace.TrainDiffusionUnetHybridWorkspace
checkpoint:
    save_last_ckpt: false
    save_last_snapshot: false
    topk:
        format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
        k: 3
        mode: max
        monitor_key: test_mean_score
dataloader:
    batch_size: 64
    num_workers: 8
    persistent_workers: false
    pin_memory: true
    shuffle: true
dataset_obs_steps: 2
ema:
    _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
    inv_gamma: 1.0
    max_value: 0.9999
    min_value: 0.0
    power: 0.75
    update_after_step: 0
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
    group: null
    id: null
    mode: online
    name: pusht
    project: pusht
    resume: true
    tags:
        - train_flow_unet_hybrid
        - pusht_image
        - default
multi_run:
    run_dir: data/outputs/flow
    wandb_name_base: flow
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_flow_unet_hybrid
obs_as_global_cond: true
optimizer:
    _target_: torch.optim.AdamW
    betas:
        - 0.95
        - 0.999
    eps: 1.0e-08
    lr: 0.0001
    weight_decay: 1.0e-06
past_action_visible: false
policy:
    _target_: diffusion_policy.policy.L1Flow_unet_hybrid_image_policy.L1FlowUnetHybridImagePolicy
    cond_predict_scale: true
    crop_shape:
        - 84
        - 84
    diffusion_step_embed_dim: 128
    down_dims:
        - 512
        - 1024
        - 2048
    eval_fixed_crop: true
    rot_aug: false
    horizon: 16
    kernel_size: 5
    n_action_steps: 8
    n_groups: 8
    n_obs_steps: 2
    noise_scheduler: # not used
        _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
        beta_end: 0.02
        beta_schedule: squaredcos_cap_v2
        beta_start: 0.0001
        clip_sample: true
        num_train_timesteps: 100
        prediction_type: epsilon
        variance_type: fixed_small

    #------------------------------------------------------------------------------
    # Configuration Options (adjust as needed):
    #------------------------------------------------------------------------------

    # infer_strategy: Inference strategy.
    #   - "L1Flow": (recommended) Our proposed two-step inference method.
    #   - "FM":     Standard flow-matching inference, i.e., Euler integration over [0,1].
    infer_strategy: L1Flow

    # num_inference_steps: Number of inference steps.
    #   - Only effective for in `FM`.
    #   - Ignored in "L1Flow", which uses a fixed two-step inference process.
    num_inference_steps: 2

    # t_first: Initial time point for the first inference step.
    #   - Only used in "L1Flow".
    #   - Recommended value: 0.5.
    t_first: 0.5

    # loss_type: Type of loss function.
    #   - Options: "l1" (recommended) or "mse".
    loss_type: l1

    # loss_space: Target loss space for supervision.
    #   - Options: "sample" (default) or "velocity".
    loss_space: sample

    # timestep_sampler_type: Timesteps sampling strategy
    #   - Options: "uniform", "beta", or "mixed" (recommended for balanced coverage).
    timestep_sampler_type: mixed
    #------------------------------------------------------------------------------

    obs_as_global_cond: true
    obs_encoder_group_norm: true
    shape_meta:
        action:
            shape:
                - 2
        obs:
            agent_pos:
                shape:
                    - 2
                type: low_dim
            image:
                shape:
                    - 3
                    - 96
                    - 96
                type: rgb
shape_meta:
    action:
        shape:
            - 2
    obs:
        agent_pos:
            shape:
                - 2
            type: low_dim
        image:
            shape:
                - 3
                - 96
                - 96
            type: rgb
task:
    dataset:
        _target_: diffusion_policy.dataset.pusht_image_dataset.PushTImageDataset
        horizon: 16
        max_train_episodes: 90
        pad_after: 7
        pad_before: 1
        seed: 42
        val_ratio: 0.02
        zarr_path: data/pusht/pusht_cchi_v7_replay.zarr
    env_runner:
        _target_: diffusion_policy.env_runner.pusht_image_runner.PushTImageRunner
        fps: 10
        legacy_test: true
        max_steps: 300
        n_action_steps: 8
        n_envs: null
        n_obs_steps: 2
        n_test: 100
        n_test_vis: 4
        n_train: 6
        n_train_vis: 2
        past_action: false
        test_start_seed: 100000
        train_start_seed: 0
    image_shape:
        - 3
        - 96
        - 96
    name: pusht_image
    shape_meta:
        action:
            shape:
                - 2
        obs:
            agent_pos:
                shape:
                    - 2
                type: low_dim
            image:
                shape:
                    - 3
                    - 96
                    - 96
                type: rgb
task_name: pusht_image
training:
    checkpoint_every: 5
    debug: false
    device: cuda:0
    gradient_accumulate_every: 1
    lr_scheduler: cosine
    lr_warmup_steps: 500
    max_train_steps: null
    max_val_steps: null
    num_epochs: 200
    resume: true
    rollout_every: 5
    sample_every: 5
    seed: 42
    tqdm_interval_sec: 1.0
    use_ema: true
    val_every: 1
val_dataloader:
    batch_size: 64
    num_workers: 8
    persistent_workers: false
    pin_memory: true
    shuffle: false
